### ISSUE TITLE
run error: Missing configuration for language

### ISSUE THREAD

**Issue by nicole8806** [rob-mccann/Pi-Voice#10]
## Hi, there, I followed all the install steps, but get the error bellow:

xuy@ubuntu:~/Pi-Voice$ python listen.py 
Traceback (most recent call last):
  File "listen.py", line 6, in <module>
    from actions.db import DBPedia
  File "/home/xuy/Pi-Voice/actions/db.py", line 18, in <module>
    dbpedia = quepy.install("actions.dbpedia")
  File "/usr/local/lib/python2.7/dist-packages/quepy/quepyapp.py", line 45, in install
    return QuepyApp(**modules)
  File "/usr/local/lib/python2.7/dist-packages/quepy/quepyapp.py", line 76, in **init**
    raise ValueError("Missing configuration for language")
ValueError: Missing configuration for language

**Comment by nicole8806** [comment]
my env:

xuy@ubuntu:~/Pi-Voice$ pip freeze --local
PyAudio==0.2.9
Python-Audio-Tools==2.16
REfO==0.13
SPARQLWrapper==1.7.6
isodate==0.5.4
keepalive==0.5
nltk==3.2
pydub==0.16.3
pyparsing==2.1.1
quepy==0.2
rdflib==4.2.1
request==0.0.2
wolframalpha==2.3
