### ISSUE TITLE
Traceback Missing configuration for language 

### ISSUE THREAD

**Issue by dangarthwaite** [rob-mccann/Pi-Voice#9]
I get the following traceback:

```
    Traceback (most recent call last):
  File "listen.py", line 6, in <module>
    from actions.db import DBPedia
  File "/home/dan/Projects/pi-voice/Pi-Voice/actions/db.py", line 18, in <module>
    dbpedia = quepy.install("actions.dbpedia")
  File "/home/dan/Projects/pi-voice/venv/local/lib/python2.7/site-packages/quepy/quepyapp.py", line 45, in install
    return QuepyApp(**modules)
  File "/home/dan/Projects/pi-voice/venv/local/lib/python2.7/site-packages/quepy/quepyapp.py", line 76, in __init__
    raise ValueError("Missing configuration for language")
ValueError: Missing configuration for language
```

Here is the virtualenv:

```
    $ pip freeze --local
    PyAudio==0.2.8
    REfO==0.13
    SPARQLWrapper==1.6.4
    html5lib==0.999
    isodate==0.5.1
    nltk==3.0.0
    numpy==1.9.1
    pyparsing==2.0.3
    quepy==0.2
    rdflib==4.1.2
    six==1.8.0
    wolframalpha==1.2
```

**Comment by dangarthwaite** [comment]
Needed to install audiotools into virtualenv.  You can't pip install audiotools.

**Comment by ojixzzz** [comment]
I get the same problem. how to handle? @dangarthwaite

**Comment by nicole8806** [comment]
@dangarthwaite , I have installed audiotools, but why still have the Missing configuration for language error?

xuy@ubuntu:~/Pi-Voice$ pip freeze --local
PyAudio==0.2.9
Python-Audio-Tools==2.16
REfO==0.13
SPARQLWrapper==1.7.6
isodate==0.5.4
keepalive==0.5
nltk==3.2
pydub==0.16.3
pyparsing==2.1.1
quepy==0.2
rdflib==4.2.1
request==0.0.2
wolframalpha==2.3

**Comment by dangarthwaite** [comment]
I don't have any more insight, guys, I've moved on from this project.
